services:
  database:
    ports:
      - "5432:5432"

  app:
    build:
      target: dev
    environment:
      NODE_ENV: development
      DISABLE_SOCKET_IO: "0"
      SOCKET_PUBLIC_URL: http://localhost:3000
      SOCKET_CORS_ORIGIN: http://localhost:3000
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - app_next:/app/.next
      - app_generated_prisma:/app/generated/prisma
    healthcheck:
      start_period: 40s

volumes:
  app_generated_prisma:
  app_node_modules:
  app_next:
